### ISSUE TITLE
Resend doesn't work in next js routes

### ISSUE THREAD

**Issue by seanroades** [resendlabs/resend-nextjs-app-router-example#4]
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.

The error was caused by importing 'resend/build/src/index.js' in './app/api/resend/route.ts'.

Resend doesn't work in next js routes

**Comment by pranayaryal** [comment]
When I upgraded to Next 14 https://nextjs.org/docs/pages/building-your-application/upgrading/version-14
this error went away

**Comment by CodyBontecou** [comment]
@pranayaryal suggestion worked for me. Thank you.
