### ISSUE TITLE
The example where in we pass the `EmailTemplate` component to the `react` key, gives an error.

### ISSUE THREAD

**Issue by dhruvaagrawal** [resendlabs/resend-nextjs-app-router-example#5]
From the example at [Resend Next.js Example](https://resend.com/docs/send-with-nextjs#3-send-email-using-react), we do:
```ts
react: EmailTemplate({ firstName: "John" })
```

Here, the `EmailTemplate` React component is passed as a callable, with the `firstName` prop sent as a JS / TS object key-value pair. In VS Code, it gives the below error:
```
Argument of type '{ from: string; to: string[]; subject: string; react: ReactNode; }' is not assignable to parameter of type 'CreateEmailOptions'.
  Type '{ from: string; to: string[]; subject: string; react: ReactNode; }' is not assignable to type 'Required<Pick<CreateEmailBaseOptions, "text">> & Partial<Pick<CreateEmailBaseOptions, "react" | "html">> & { ...; }'.
    Property 'text' is missing in type '{ from: string; to: string[]; subject: string; react: ReactNode; }' but required in type 'Required<Pick<CreateEmailBaseOptions, "text">>'.
```

This error is fixed by passing it as a component instead of the callable, like so:
```ts
react: <EmailTemplate firstName="Dev" />
```

**Comment by dhruvaagrawal** [comment]
This seems to work as expected if the example repository is forked and cloned. But in a project wherein the same dependencies with the same versions are present, the above error comes in. Not sure whether this is still an issue, or it is localised to my setup. Closing it for now since I cannot recreate this, but if someone can help me on this, please do let me know,

**Comment by sirvine** [comment]
FWIW I ran into the same error using resend 0.17.1 & typescript 5.1.6.

**Comment by dhruvaagrawal** [comment]
Oh okay, @sirvine. I have not looked into this issue for now, but if you find a solution to this, please do let me know.
